<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Section;
use App\Models\ClassModel;
use Carbon\Carbon;

class SectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data safely (respecting foreign key constraints)
        Section::query()->delete();

        // Get mapping of old class IDs to new class IDs
        $classMapping = $this->getClassMapping();

        $sections = [
            [
                'id' => 1,
                'name' => 'A',
                'category' => 'Primary',
                'capacity' => 50,
                'class_id' => $classMapping[1] ?? null,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-01 04:37:09'),
                'updated_at' => Carbon::parse('2023-05-01 04:37:09'),
            ],
            [
                'id' => 2,
                'name' => 'B',
                'category' => 'Primary',
                'capacity' => 50,
                'class_id' => $classMapping[2] ?? null,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-01 04:37:25'),
                'updated_at' => Carbon::parse('2023-05-01 04:37:25'),
            ],
            [
                'id' => 3,
                'name' => '2-A',
                'category' => '2-A',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 10:45:08'),
                'updated_at' => Carbon::parse('2025-05-02 10:19:45'),
            ],
            [
                'id' => 4,
                'name' => '2-G',
                'category' => '2-G',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 10:46:05'),
                'updated_at' => Carbon::parse('2025-05-02 10:19:33'),
            ],
            [
                'id' => 5,
                'name' => 'M2-A',
                'category' => 'M2-A',
                'capacity' => 50,
                'class_id' => 26,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:32:04'),
                'updated_at' => Carbon::parse('2025-05-19 08:37:16'),
            ],
            [
                'id' => 6,
                'name' => '4-B',
                'category' => '4-B',
                'capacity' => 50,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:32:44'),
                'updated_at' => Carbon::parse('2025-05-02 09:13:59'),
            ],
            [
                'id' => 7,
                'name' => 'M2-B',
                'category' => 'M2-B',
                'capacity' => 50,
                'class_id' => 26,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:33:30'),
                'updated_at' => Carbon::parse('2025-05-19 08:38:20'),
            ],
            [
                'id' => 9,
                'name' => 'Prep-A',
                'category' => 'Prep-A',
                'capacity' => 50,
                'class_id' => 27,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:34:47'),
                'updated_at' => Carbon::parse('2025-05-02 10:25:50'),
            ],
            [
                'id' => 10,
                'name' => 'Prep-S',
                'category' => 'Prep-S',
                'capacity' => 50,
                'class_id' => 27,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:36:21'),
                'updated_at' => Carbon::parse('2025-05-02 10:26:04'),
            ],
            [
                'id' => 11,
                'name' => '6-B',
                'category' => '6-B',
                'capacity' => 50,
                'class_id' => 20,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:39:57'),
                'updated_at' => Carbon::parse('2023-08-21 11:39:42'),
            ],
            [
                'id' => 12,
                'name' => 'G1-A',
                'category' => 'G1-A',
                'capacity' => 50,
                'class_id' => 28,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:40:40'),
                'updated_at' => Carbon::parse('2025-05-20 11:29:24'),
            ],
            [
                'id' => 14,
                'name' => '2-B',
                'category' => '2-B',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:43:17'),
                'updated_at' => Carbon::parse('2025-05-02 10:20:41'),
            ],
            [
                'id' => 17,
                'name' => '4-G',
                'category' => '4-G',
                'capacity' => 50,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:48:20'),
                'updated_at' => Carbon::parse('2025-05-02 09:14:10'),
            ],
            [
                'id' => 18,
                'name' => '4-S',
                'category' => '4-S',
                'capacity' => 50,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:48:39'),
                'updated_at' => Carbon::parse('2025-05-02 09:14:17'),
            ],
            [
                'id' => 22,
                'name' => 'G6-S',
                'category' => 'G6-S',
                'capacity' => 50,
                'class_id' => 20,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:52:00'),
                'updated_at' => Carbon::parse('2025-05-19 08:07:57'),
            ],
            [
                'id' => 27,
                'name' => 'G9-B',
                'category' => 'G9-B',
                'capacity' => 100,
                'class_id' => 23,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:57:47'),
                'updated_at' => Carbon::parse('2025-05-15 08:38:40'),
            ],
            [
                'id' => 28,
                'name' => 'G9-G',
                'category' => 'G9-G',
                'capacity' => 100,
                'class_id' => 23,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 11:58:45'),
                'updated_at' => Carbon::parse('2025-05-03 03:39:48'),
            ],
            [
                'id' => 29,
                'name' => 'G11-B',
                'category' => 'G11-B',
                'capacity' => 50,
                'class_id' => 25,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:02:39'),
                'updated_at' => Carbon::parse('2025-05-02 01:32:08'),
            ],
            [
                'id' => 30,
                'name' => 'M2-S',
                'category' => 'M2-S',
                'capacity' => 50,
                'class_id' => 26,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:04:24'),
                'updated_at' => Carbon::parse('2025-05-19 08:38:56'),
            ],
            [
                'id' => 32,
                'name' => 'Prep-B',
                'category' => 'Prep-B',
                'capacity' => 50,
                'class_id' => 27,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:07:25'),
                'updated_at' => Carbon::parse('2025-05-02 10:26:18'),
            ],
            [
                'id' => 33,
                'name' => 'Prep-K',
                'category' => 'Prep-K',
                'capacity' => 50,
                'class_id' => 27,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:07:46'),
                'updated_at' => Carbon::parse('2025-05-02 10:26:43'),
            ],
            [
                'id' => 34,
                'name' => 'G11-G',
                'category' => 'G11-G',
                'capacity' => 50,
                'class_id' => 25,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:08:43'),
                'updated_at' => Carbon::parse('2025-05-02 01:32:18'),
            ],
            [
                'id' => 36,
                'name' => 'G1-B',
                'category' => 'G1-B',
                'capacity' => 50,
                'class_id' => 28,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:10:18'),
                'updated_at' => Carbon::parse('2025-05-20 11:29:55'),
            ],
            [
                'id' => 38,
                'name' => 'PA',
                'category' => 'PA',
                'capacity' => 50,
                'class_id' => 29,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:40:09'),
                'updated_at' => Carbon::parse('2025-05-02 09:33:08'),
            ],
            [
                'id' => 40,
                'name' => 'A',
                'category' => 'A',
                'capacity' => 50,
                'class_id' => 29,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 01:11:38'),
                'updated_at' => Carbon::parse('2023-05-16 01:11:38'),
            ],
            [
                'id' => 41,
                'name' => 'G10-B',
                'category' => 'G10-B',
                'capacity' => 50,
                'class_id' => 24,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-07-05 08:18:48'),
                'updated_at' => Carbon::parse('2025-05-02 01:31:34'),
            ],
            [
                'id' => 44,
                'name' => '2-K',
                'category' => '2-K',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:35:35'),
                'updated_at' => Carbon::parse('2025-05-02 09:17:09'),
            ],
            [
                'id' => 45,
                'name' => '2-S',
                'category' => '2-S',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:35:54'),
                'updated_at' => Carbon::parse('2025-05-02 09:17:30'),
            ],
            [
                'id' => 49,
                'name' => 'G10-G',
                'category' => 'G10-G',
                'capacity' => 50,
                'class_id' => 24,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:43:19'),
                'updated_at' => Carbon::parse('2025-05-02 01:31:47'),
            ],
            [
                'id' => 50,
                'name' => 'M2-G',
                'category' => 'M2-G',
                'capacity' => 50,
                'class_id' => 26,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:45:52'),
                'updated_at' => Carbon::parse('2025-05-19 08:39:31'),
            ],
            [
                'id' => 51,
                'name' => 'Prep-G',
                'category' => 'Prep-G',
                'capacity' => 50,
                'class_id' => 27,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:46:54'),
                'updated_at' => Carbon::parse('2025-05-02 10:26:56'),
            ],
            [
                'id' => 52,
                'name' => 'G1-G',
                'category' => 'G1-G',
                'capacity' => 50,
                'class_id' => 28,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:49:09'),
                'updated_at' => Carbon::parse('2025-05-20 11:30:53'),
            ],
            [
                'id' => 53,
                'name' => 'G1-S',
                'category' => 'G1-S',
                'capacity' => 50,
                'class_id' => 28,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:49:52'),
                'updated_at' => Carbon::parse('2025-05-20 11:32:01'),
            ],
            [
                'id' => 54,
                'name' => 'G7-S',
                'category' => 'G7-S',
                'capacity' => 50,
                'class_id' => 21,
                'note' => null,
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2023-01-01 00:00:00'),
            ],
            [
                'id' => 55,
                'name' => 'G2-S',
                'category' => 'G2-S',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:45:07'),
            ]
        ];

        // Add more sections from the data...
        $moreSections = [
            [
                'id' => 56,
                'name' => 'G7-B',
                'category' => 'G7-B',
                'capacity' => 50,
                'class_id' => 21,
                'note' => null,
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2023-01-01 00:00:00'),
            ],
            [
                'id' => 57,
                'name' => 'G2-B',
                'category' => 'G2-B',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:43:56'),
            ],
            [
                'id' => 58,
                'name' => 'G2-A',
                'category' => 'G2-A',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-02 09:18:40'),
            ],
            [
                'id' => 59,
                'name' => 'G6-B',
                'category' => 'G6-B',
                'capacity' => 50,
                'class_id' => 20,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-19 08:06:46'),
            ],
            [
                'id' => 60,
                'name' => 'G8-B',
                'category' => 'G8-B',
                'capacity' => 50,
                'class_id' => 22,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-19 08:09:15'),
            ],
            [
                'id' => 61,
                'name' => 'G2-G',
                'category' => 'G2-G',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:44:25'),
            ],
            [
                'id' => 62,
                'name' => 'G6-G',
                'category' => 'G6-G',
                'capacity' => 50,
                'class_id' => 20,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-19 08:07:15'),
            ],
            [
                'id' => 63,
                'name' => 'G8-A',
                'category' => 'G8-A',
                'capacity' => 50,
                'class_id' => 22,
                'note' => null,
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2023-01-01 00:00:00'),
            ],
            [
                'id' => 64,
                'name' => 'G8-G',
                'category' => 'G8-G',
                'capacity' => 50,
                'class_id' => 22,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-19 08:09:48'),
            ],
            [
                'id' => 65,
                'name' => 'G7-G',
                'category' => 'G7-G',
                'capacity' => 50,
                'class_id' => 21,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-19 08:08:40'),
            ],
            [
                'id' => 66,
                'name' => 'G8-S',
                'category' => 'G8-S',
                'capacity' => 50,
                'class_id' => 22,
                'note' => null,
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2023-01-01 00:00:00'),
            ],
            [
                'id' => 67,
                'name' => 'G2-K',
                'category' => 'G2-K',
                'capacity' => 50,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-02 09:19:15'),
            ],
            [
                'id' => 71,
                'name' => 'G5-B',
                'category' => 'G5-B',
                'capacity' => 50,
                'class_id' => 19,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:41:48'),
            ],
            [
                'id' => 72,
                'name' => 'G4-B',
                'category' => 'G4-B',
                'capacity' => 50,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:39:58'),
            ],
            [
                'id' => 73,
                'name' => 'G3-B',
                'category' => 'G3-B',
                'capacity' => 50,
                'class_id' => 16,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:45:50'),
            ],
            [
                'id' => 74,
                'name' => 'G4-S',
                'category' => 'G4-S',
                'capacity' => 50,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:41:16'),
            ],
            [
                'id' => 75,
                'name' => 'G5-G',
                'category' => 'G5-G',
                'capacity' => 50,
                'class_id' => 19,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:42:05'),
            ],
            [
                'id' => 76,
                'name' => 'G3-S',
                'category' => 'G3-S',
                'capacity' => 50,
                'class_id' => 16,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:47:10'),
            ],
            [
                'id' => 79,
                'name' => 'New Admission Grade 5',
                'category' => 'New Admission Grade 5',
                'capacity' => 1000,
                'class_id' => 19,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-09-28 15:13:59'),
                'updated_at' => Carbon::parse('2025-05-07 04:27:23'),
            ],
            [
                'id' => 80,
                'name' => 'G3-G',
                'category' => 'G3-G',
                'capacity' => 50,
                'class_id' => 16,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:46:48'),
            ],
            [
                'id' => 81,
                'name' => 'G4-G',
                'category' => 'G4-G',
                'capacity' => 50,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-01-01 00:00:00'),
                'updated_at' => Carbon::parse('2025-05-17 01:40:33'),
            ],
            [
                'id' => 82,
                'name' => 'G10-S',
                'category' => 'G10-S',
                'capacity' => 50,
                'class_id' => 24,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:43:19'),
                'updated_at' => Carbon::parse('2023-08-21 11:44:06'),
            ],
            [
                'id' => 83,
                'name' => 'G12-A',
                'category' => 'G12-A',
                'capacity' => 50,
                'class_id' => 12,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:08:43'),
                'updated_at' => Carbon::parse('2023-05-16 12:08:43'),
            ],
            [
                'id' => 84,
                'name' => 'G12-B',
                'category' => 'G12-B',
                'capacity' => 50,
                'class_id' => 12,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:08:43'),
                'updated_at' => Carbon::parse('2025-05-02 01:32:36'),
            ],
            [
                'id' => 85,
                'name' => 'G12-G',
                'category' => 'G12-G',
                'capacity' => 50,
                'class_id' => 12,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:08:43'),
                'updated_at' => Carbon::parse('2025-05-02 01:32:48'),
            ],
            [
                'id' => 86,
                'name' => 'G12-S',
                'category' => 'G12-S',
                'capacity' => 50,
                'class_id' => 12,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-05-16 12:08:43'),
                'updated_at' => Carbon::parse('2023-05-16 12:08:43'),
            ],
            [
                'id' => 87,
                'name' => 'New Admission Montessori 2',
                'category' => 'New Admission Montessori 2',
                'capacity' => 1000,
                'class_id' => 26,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-08-21 11:45:52'),
                'updated_at' => Carbon::parse('2025-05-07 04:31:45'),
            ],
            [
                'id' => 88,
                'name' => 'New Admission Grade Prep',
                'category' => 'New Admission Grade Prep',
                'capacity' => 1000,
                'class_id' => 27,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2023-11-08 10:34:37'),
                'updated_at' => Carbon::parse('2025-05-07 04:31:23'),
            ],
            [
                'id' => 89,
                'name' => 'New Admission Montessori 1',
                'category' => 'New Admission Montessori 1',
                'capacity' => 1000,
                'class_id' => 30,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-02 08:17:49'),
                'updated_at' => Carbon::parse('2025-05-07 04:32:07'),
            ],
            [
                'id' => 90,
                'name' => 'New Admission Grade 1',
                'category' => 'New Admission Grade 1',
                'capacity' => 1000,
                'class_id' => 28,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:20:37'),
                'updated_at' => Carbon::parse('2025-05-07 04:20:37'),
            ],
            [
                'id' => 91,
                'name' => 'New Admission Grade 2',
                'category' => 'New Admission Grade 2',
                'capacity' => 1000,
                'class_id' => 15,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:23:32'),
                'updated_at' => Carbon::parse('2025-05-07 04:23:32'),
            ],
            [
                'id' => 92,
                'name' => 'New Admission Grade 3',
                'category' => 'New Admission Grade 3',
                'capacity' => 1000,
                'class_id' => 16,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:24:56'),
                'updated_at' => Carbon::parse('2025-05-07 04:24:56'),
            ],
            [
                'id' => 93,
                'name' => 'New Admission Grade 4',
                'category' => 'New Admission Grade 4',
                'capacity' => 1000,
                'class_id' => 17,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:26:39'),
                'updated_at' => Carbon::parse('2025-05-07 04:26:39'),
            ],
            [
                'id' => 94,
                'name' => 'New Admission Grade 6',
                'category' => 'New Admission Grade 6',
                'capacity' => 1000,
                'class_id' => 20,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:27:46'),
                'updated_at' => Carbon::parse('2025-05-07 04:27:46'),
            ],
            [
                'id' => 95,
                'name' => 'New Admission Grade 7',
                'category' => 'New Admission Grade 7',
                'capacity' => 1000,
                'class_id' => 21,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:28:35'),
                'updated_at' => Carbon::parse('2025-05-07 04:28:35'),
            ],
            [
                'id' => 96,
                'name' => 'New Admission Grade 8',
                'category' => 'New Admission Grade 8',
                'capacity' => 1000,
                'class_id' => 22,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:29:08'),
                'updated_at' => Carbon::parse('2025-05-07 04:29:08'),
            ],
            [
                'id' => 97,
                'name' => 'New Admission Grade 9',
                'category' => 'New Admission Grade 9',
                'capacity' => 1000,
                'class_id' => 23,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:29:41'),
                'updated_at' => Carbon::parse('2025-05-07 04:29:41'),
            ],
            [
                'id' => 98,
                'name' => 'New Admission Grade 10',
                'category' => 'New Admission Grade 10',
                'capacity' => 1000,
                'class_id' => 24,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:30:05'),
                'updated_at' => Carbon::parse('2025-05-07 04:30:05'),
            ],
            [
                'id' => 99,
                'name' => 'New Admission Grade 11',
                'category' => 'New Admission Grade 11',
                'capacity' => 1000,
                'class_id' => 25,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:30:30'),
                'updated_at' => Carbon::parse('2025-05-07 04:30:30'),
            ],
            [
                'id' => 100,
                'name' => 'New Admission Grade 12',
                'category' => 'New Admission Grade 12',
                'capacity' => 1000,
                'class_id' => 12,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-07 04:30:57'),
                'updated_at' => Carbon::parse('2025-05-07 04:30:57'),
            ],
            [
                'id' => 101,
                'name' => 'G5-S',
                'category' => 'G5-S',
                'capacity' => 50,
                'class_id' => 19,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-17 10:35:29'),
                'updated_at' => Carbon::parse('2025-05-17 01:42:32'),
            ],
            [
                'id' => 102,
                'name' => 'M1-A',
                'category' => 'M1-A',
                'capacity' => 50,
                'class_id' => 30,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-19 08:41:38'),
                'updated_at' => Carbon::parse('2025-05-19 08:41:38'),
            ],
            [
                'id' => 103,
                'name' => 'M1-B',
                'category' => 'M1-B',
                'capacity' => 50,
                'class_id' => 30,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-19 08:42:20'),
                'updated_at' => Carbon::parse('2025-05-19 08:42:20'),
            ],
            [
                'id' => 104,
                'name' => 'M1-G',
                'category' => 'M1-G',
                'capacity' => 50,
                'class_id' => 30,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-19 08:43:02'),
                'updated_at' => Carbon::parse('2025-05-19 08:43:02'),
            ],
            [
                'id' => 105,
                'name' => 'M1-S',
                'category' => 'M1-S',
                'capacity' => 50,
                'class_id' => 30,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-19 08:43:45'),
                'updated_at' => Carbon::parse('2025-05-19 08:43:45'),
            ],
            [
                'id' => 106,
                'name' => 'G1-K',
                'category' => 'G1-K',
                'capacity' => 50,
                'class_id' => 28,
                'note' => '',
                'created_by' => 'Super Admin User',
                'updated_by' => 'Super Admin User',
                'created_at' => Carbon::parse('2025-05-20 11:33:01'),
                'updated_at' => Carbon::parse('2025-05-20 11:33:01'),
            ],
        ];

        // Merge all sections
        $allSections = array_merge($sections, $moreSections);

        // Filter out sections where class_id doesn't exist and insert the rest
        $validSections = array_filter($allSections, function ($section) {
            return $section['class_id'] !== null && ClassModel::find($section['class_id']) !== null;
        });

        foreach ($validSections as $section) {
            Section::create($section);
        }

        $this->command->info('Sections seeded successfully! Total sections: ' . count($validSections));
    }

    /**
     * Get mapping of old class IDs to new class IDs
     */
    private function getClassMapping(): array
    {
        // For sections that reference non-existent classes, we'll map them to existing ones
        return [
            1 => 28, // Map to Grade 1
            2 => 15, // Map to Grade 2
            18 => 17, // Map to Grade 4 (some sections reference classID 18 which doesn't exist)
        ];
    }
}
